name: Argos test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  argos:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run Argos
        run: git rev-parse HEAD
