name: Argos upload
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  argos:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm ci
      - run: git config remote.origin.fetch "+refs/heads/*:refs/remotes/origin/*"
      - run: git fetch origin HEAD --depth 50
      - run: git fetch origin main:main --depth 50
      - run: git merge-base HEAD main
      - name: Upload screenshots
        run: npm exec -- argos upload screenshots
        env:
          DEBUG: "@argos-ci/core"
          ARGOS_TOKEN: d808f6191835dc07380fe6e22460db7b46313b6e
          ARGOS_API_BASE_URL: https://1e6c-93-19-70-152.ngrok-free.app/v2
