name: Debug repository_dispatch
on:
  repository_dispatch:
jobs:
  log-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print event type
        run: 'echo "Event type: ${{ github.event.action }}"'
      - name: Print full payload
        run: echo '${{ toJSON(github.event.client_payload) }}'
      - name: Print full event
        run: echo '${{ toJSON(github.event) }}'
